# Generated by Django 4.2.2 on 2023-07-12 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0003_rename_entered_by_doctor_details_enter_by'),
        ('products', '0002_remove_products_enterd_by_products_enterd_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='deals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_id', models.CharField(blank=True, max_length=300)),
                ('quantity', models.IntegerField(default=1)),
                ('totalPrice', models.FloatField(default=0.0)),
                ('Product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
                ('doctor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor_details')),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
