# Generated by Django 4.2.2 on 2023-07-11 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0003_rename_entered_by_doctor_details_enter_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField(auto_now_add=True)),
                ('Schedule_time', models.TimeField(auto_now_add=True)),
                ('doct_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor_details')),
                ('enterd_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
