# Generated by Django 4.2.2 on 2023-07-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Schedule_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='schedule_date',
            field=models.DateField(),
        ),
    ]
