# Generated by Django 4.2.2 on 2023-07-11 19:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_appointment_schedule_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Schedule_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='schedule_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
