# Generated by Django 4.2.2 on 2023-07-11 20:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_appointment_schedule_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Schedule_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
