# Generated by Django 4.2.2 on 2023-07-12 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointment', '0004_alter_appointment_schedule_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='enterd_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
