# Generated by Django 4.2.2 on 2023-07-12 07:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_alter_appointment_enterd_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Schedule_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
