# Generated by Django 4.2.2 on 2023-07-11 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_doctor_details_entered_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor_details',
            old_name='entered_by',
            new_name='enter_by',
        ),
    ]
